name: Node.js Package

on:
  issues:
    types: [opened, edited, milestoned]
  push:
  pull_request:
    branches:
      - master
  page_build:
  release:
    types: [created]
  delete:
  deployment:
  fork:
  label:
    types: [created, deleted]
  milestone:
    types: [opened, deleted]
  project:
    types: [created, deleted]    
  
jobs:
  send-sms:
    name: Send SMS
    runs-on: ubuntu-latest
    steps:
    - name: 'Sending SMS Notification'
      uses: SMSAlert/smsalert@master
      with:
        senderid: ${{ secrets.senderid }}
        toPhoneNumber: ${{ secrets.toPhoneNumber }}
        message: ${{ secrets.message }}
      env:
        SMSALERT_USERNAME: ${{ secrets.SMSALERT_USERNAME }}
        SMSALERT_PASSWORD: ${{ secrets.SMSALERT_PASSWORD }}
  
